---
id: Imsp
name: Imsp
full: IMSP client library
description: Provides an API into an IMSP server for address books and options.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Imsp
authors:
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 2.0.11
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Translation: ^2.2
      pear.horde.org/Horde_Util: ^2
